translate uniswap v4 whitepaper draft to Chinese
Uniswap/v4-core pull request #239
Opened 2023-06-14 19:04 UTC by AmazingAng

translated white paper pdf in whitepaper-v4-draft-zh.pdf

## Related Issue
Which issue does this pull request resolve?

## Description of changes

2023-06-15 11:08 UTC, hensha256 commented
Thanks so much for making this translation, thats awesome! Someone from our team is going to review it next week 🙌

2023-06-19 10:01 UTC, c1ay commented
Chinese comments need to be removed from the code

2023-06-19 11:00 UTC, AmazingAng commented
> Chinese comments need to be removed from the code

Chinese comments in the code are removed.

2023-06-22 13:39 UTC, antoncoding reviewed
Left some suggestions 😄

2023-06-22 13:39 UTC, antoncoding commented on latex/main-zh.tex
> +此外，在以前的\textsc{Uniswap}版本中，部署新的池需要部署新的合约，其成本随着合约字节码的大小而增加。另外，涉及到与多个\textsc{Uniswap}池的交易涉及到多个合约之间的转账和冗余状态更新。自\textsc{Uniswap v2}以来，\textsc{Uniswap}要求ETH被包装成ERC-20，而不是支持原生ETH。这些都带来了gas成本。
```suggestion
此外，在以前的\textsc{Uniswap}版本中，部署新的池需要部署新的合约，其成本随着合约大小而增加。另外，涉及到与多个\textsc{Uniswap}池的交易涉及到多个合约之间的转账和冗余状态更新。自\textsc{Uniswap v2}以来，\textsc{Uniswap}要求ETH被转换成ERC-20，而不是支持原生ETH。这些都增加了gas成本。
```

2023-06-22 13:39 UTC, antoncoding commented on latex/main-zh.tex
> +    \item \emph{闪电记账}：单例使用“闪电记账”机制，要求在锁定结束时池或调用者没有代币欠款。在调用过程中，代币可以用于单例内外的任意数量的操作。通过EIP-1153 \cite{Akhunov2018}中提议的瞬态存储操作码，这种功能将变得高效。闪电记账进一步降低了跨多个池的交易的gas成本，并支持与\textsc{Uniswap v4}的更复杂集成。
```suggestion
    \item \emph{闪电记账}：单例使用“闪电记账”机制，要求在锁定结束时池或调用者没有代币欠款。在调用过程中，代币可以用于单例内外的任意数量的操作。通过EIP-1153 \cite{Akhunov2018}中提议的瞬态存储操作码，这种功能将变得高效。闪电记账进一步降低了跨多个池的交易的gas成本，并支持与\textsc{Uniswap v4}更复杂的整合。
```

2023-06-22 13:39 UTC, antoncoding commented on latex/main-zh.tex
> +以下章节详细解释了这些变化和使它们成为可能的体系结构变化。
```suggestion
以下章节详细解释了这些变化，与成就它们的架构变化。
```

2023-06-22 13:39 UTC, antoncoding commented on latex/main-zh.tex
> +    \item \emph{原生ETH}：\textsc{Uniswap v4}恢复了对原生ETH的支持，并支持在\textsc{v4}池中使用原生代币进行配对。ETH交换者和流动性提供者从转账成本更低和去除额外包装成本中受益。
```suggestion
    \item \emph{原生ETH}：\textsc{Uniswap v4}恢复了对原生ETH的支持，并支持在\textsc{v4}池中使用原生代币进行配对。ETH交换者和流动性提供者从转账成本更低和去除额外转换成本中受益。
```

2023-06-22 13:39 UTC, antoncoding commented on latex/main-zh.tex
> +\emph{Hooks}是在池的执行过程中在指定点执行一些开发者定义的逻辑的外部部署合约。这些Hooks允许集成者创建具有灵活和可定制执行的集中流动性池。
```suggestion
\emph{Hooks}是在池的执行过程中在指定点执行一些开发者定义的逻辑的外部部署合约。这些Hooks允许整合方创建具有灵活和可自定义的集中流动性池。
```

2023-06-23 08:42 UTC, AmazingAng commented on latex/main-zh.tex
> +\emph{Hooks}是在池的执行过程中在指定点执行一些开发者定义的逻辑的外部部署合约。这些Hooks允许集成者创建具有灵活和可定制执行的集中流动性池。
I think 集成者 is better here

2023-06-23 08:44 UTC, AmazingAng commented on latex/main-zh.tex
> +以下章节详细解释了这些变化和使它们成为可能的体系结构变化。
lgtm

2023-06-23 08:45 UTC, AmazingAng commented on latex/main-zh.tex
> +    \item \emph{原生ETH}：\textsc{Uniswap v4}恢复了对原生ETH的支持，并支持在\textsc{v4}池中使用原生代币进行配对。ETH交换者和流动性提供者从转账成本更低和去除额外包装成本中受益。
I think 包装 is better

2023-06-23 15:41 UTC, wanxinwanxin commented
Original translation looks good to me. 
I'm indifferent towards edits suggested by @antoncoding , think it's decent either way.

2023-07-12 16:21 UTC, ewilz approved these changes

2023-07-13 14:47 UTC, ewilz requested changes
revoking approval. @aadams says the latex file has errors.....

2023-07-13 14:57 UTC, aadams commented
> revoking approval. @aadams says the latex file has errors.....

on further inspection, it was because i was using a different compiler. changed it and now it works. with that one fix request above we can merge!

2023-07-13 16:56 UTC, AmazingAng commented on latex/main-zh.tex
> +    \scalebox{.7225}{
> Can you lower this scalebox value so the pdf is 4 pages instead of 5?

done

2023-07-13 19:02 UTC, ewilz approved these changes

2023-07-13 19:05 UTC, merged