Reject native currency for non-native call
Uniswap/v4-core pull request #556
Opened 2024-04-04 09:57 UTC by nishim3

## Related Issue
Which issue does this pull request resolve?
#555 
## Description of changes
Added a require statement to make sure no ether is sent during a non-native currency type.

2024-04-04 11:42 UTC, hensha256 requested changes
So fast responding to that issue hahah. Just a couple of requests 🙏

2024-04-05 03:33 UTC, snreynolds commented on src/PoolManager.sol
> +            require(msg.value == 0, "msg.value should be 0 for non-native currency");
Looks like you still have not defined a custom error. You'll need to declare it in `IPoolManager.sol` and then revert with it here. You can see examples of how we declare custom errors at the top of the `IPoolManager.sol` contract

2024-04-05 03:34 UTC, snreynolds requested changes
please add custom error thanks!

2024-04-08 22:58 UTC, hensha256 requested changes
Requested a name change for the error.

Please can you add a test?
Maybe you can add a `PoolSettleTest.sol` that calls settle on the pool manager inside a lock. And then inside `PoolManager.t.sol` add `test_settle_revertsSendingNativeWithToken` and test that this new custom error is hit with `vm.expectRevert`

Its not easy, so if you would like me to do this testing let me know :)

2024-04-08 22:58 UTC, hensha256 commented on src/interfaces/IPoolManager.sol
> +    error rejectNative();
Please can it start with a capital!
Maybe `NonZeroNativeValue`

2024-04-09 02:56 UTC, nishim3 commented
@hensha256 I have changed the name. If the issue is not at upmost priority, I would like to try to code the test. I will let you know if and when I face issues.

2024-04-09 19:08 UTC, hensha256 reviewed
The test looks great!! Just a couple of comments

2024-04-09 19:08 UTC, hensha256 commented on src/test/PoolSettleTest.sol
> +        uint256 amount0;
what is the purpose of amount0 and amount1? i think you can remove them!

2024-04-09 19:08 UTC, hensha256 commented on src/test/PoolSettleTest.sol
> +    using SafeCast for uint256;
I dont think you need these 2 libraries?

2024-04-09 19:24 UTC, hensha256 commented on test/utils/Deployers.sol
> +            address(settleRouter),
i dont think this is needed - youre not transferring tokens from the settleRouter

2024-04-09 19:35 UTC, nishim3 commented
Any idea why coverage is failing?

2024-04-09 19:39 UTC, hensha256 commented
> Any idea why coverage is failing?

Just because your PR is a fork that doesnt have access to Uniswap's github secrets :) its no problem

2024-04-09 19:41 UTC, hensha256 submitted a review, later dismissed

2024-04-09 21:19 UTC, hensha256 commented
we just need @snreynolds to approve because she requested changes too
please can you merge in main? 🙏

2024-04-10 15:11 UTC, snreynolds approved these changes

2024-04-10 15:11 UTC, merged