Currency unit tests
Uniswap/v4-core pull request #596
Opened 2024-04-23 16:04 UTC by hensha256

2024-04-24 16:25 UTC, snreynolds commented
It looks like Currency.sol doesn't have full coverage - is that a mistake of the tool? You can run `forge coverage --report debug` to inspect what branches in the code are untested.

2024-05-06 19:41 UTC, dianakocsis commented
> forge coverage --report debug

I think it might be mistake of the tool. 
`Uncovered for src/types/Currency.sol:
- Statement (location: source ID 98, line 97, chars 3909-3932, hits: 0)`

It says this statement inside `isNative` isn't being covered, but it is
    function isNative(Currency currency) internal pure returns (bool) {
        return Currency.unwrap(currency) == Currency.unwrap(NATIVE);
    }

2024-05-17 15:56 UTC, hensha256 commented on src/test/DynamicReturnFeeTestHook.sol
> +        view
compiler warning on main rn

2024-05-17 16:07 UTC, dianakocsis requested changes

2024-05-17 18:17 UTC, dianakocsis commented on src/test/DynamicReturnFeeTestHook.sol
> +        view
nice noticed this too

2024-05-17 18:43 UTC, dianakocsis requested changes

2024-05-17 18:43 UTC, dianakocsis commented on test/types/Currency.t.sol
> +    function test_fuzz_balanceOf_native(uint256 amount) public {
can you assert that the currencyTest balance is the prev balance minus amount here too?

2024-05-17 18:43 UTC, dianakocsis commented on test/types/Currency.t.sol
> +    function test_fuzz_balanceOf_native(uint256 amount) public {
as well as `test_fuzz_balanceOf_token`, `test_fuzz_transfer_native`, and `test_fuzz_transfer_token`

2024-05-17 19:17 UTC, dianakocsis approved these changes

2024-05-17 19:19 UTC, merged