Rename Instances of "Delta" to "Deltas"
Uniswap/v4-core pull request #738
Opened 2024-06-04 21:40 UTC by Jun1on

## Related Issue

BalanceDelta and BeforeSwapDelta are custom types of 2 int128s packed into a single 32 byte slot. However, other contexts like CurrencyDelta refer to a single value.

This singular naming scheme is confusing.

## Description of changes

Rename BalanceDelta, BeforeSwapDelta, and other "delta" namings to plural form.
Rename hook flags to "ReturnDelta**s**" except for afterSwap (which only returns one delta).

2024-06-06 08:00 UTC, nishim3 commented
Just renaming the variables generally does not cause such a large gas difference

2024-06-10 14:43 UTC, Jun1on commented
these gas snapshots changed regardless of the name change (just cloning main and running forget test)

2024-06-10 15:04 UTC, nishim3 commented
> these gas snapshots changed regardless of the name change (just cloning main and running forge test)

Do you run using --isolate?

2024-06-11 18:18 UTC, snreynolds requested changes

2024-06-11 18:18 UTC, snreynolds commented on src/interfaces/IHooks.sol
> +    /// @param deltas The amount owed to the caller (positive) or owed to the pool (negative)
the amounts

2024-06-11 18:18 UTC, snreynolds commented on src/interfaces/IHooks.sol
> +    /// @return BeforeSwapDeltas The hook's delta in specified and unspecified currencies. Positive: the hook is owed/took currency, negative: the hook owes/sent currency
deltas

2024-06-11 18:18 UTC, snreynolds commented on src/interfaces/IPoolManager.sol
>      /// @return feeDelta The balance delta of the fees generated in the liquidity range. Returned for informational purposes.
feeDeltas

2024-06-11 18:18 UTC, snreynolds commented on src/interfaces/IPoolManager.sol
>      /// @return feeDelta The balance delta of the fees generated in the liquidity range. Returned for informational purposes.
and balance deltas

2024-06-11 18:18 UTC, snreynolds commented on src/interfaces/IPoolManager.sol
>      /// @return feeDelta The balance delta of the fees generated in the liquidity range. Returned for informational purposes.
can you actually change feeDelta -> feesAccrued to match the named return param in PoolManager.sol

2024-06-11 18:18 UTC, snreynolds commented on src/libraries/Hooks.sol
> +                    amountToSwap += hookDeltaspecified;
same with L271, L273, and L268 - they should all still be `hookDeltaSpecified` because it is only pertaining to one delta in the token specified

2024-06-11 18:18 UTC, snreynolds commented on src/libraries/Hooks.sol
> +                int128 hookDeltaspecified = hookReturn.getSpecifiedDelta();
this should just be hookDeltaSpecified bc it is only concerning one delta in the specified token

2024-06-11 18:18 UTC, snreynolds commented on src/libraries/Hooks.sol
> +        int128 hookDeltaspecified = beforeSwapHookReturn.getSpecifiedDelta();
```suggestion
        int128 hookDeltaSpecified = beforeSwapHookReturn.getSpecifiedDelta();
```

2024-06-11 18:18 UTC, snreynolds commented on src/libraries/Hooks.sol
> +        int128 hookDeltaspecified = beforeSwapHookReturn.getSpecifiedDelta();
camelCase

2024-06-11 18:18 UTC, snreynolds commented on src/libraries/ParseBytes.sol
> -    function parseReturnDelta(bytes memory result) internal pure returns (int256 hookReturn) {
comment here about it being a delta in the after swap case

2024-06-11 18:18 UTC, snreynolds commented on src/test/BaseTestHooks.sol
> +        BalanceDeltas, /* delta **/
update comment

2024-06-11 18:18 UTC, snreynolds commented on src/test/BaseTestHooks.sol
> +        BalanceDeltas, /* delta **/
update comment

2024-06-11 18:18 UTC, snreynolds commented on src/test/BaseTestHooks.sol
> +        BalanceDeltas, /* delta **/
update comment

2024-06-11 18:18 UTC, snreynolds commented on src/test/DeltaReturningHook.sol
> +        BalanceDeltas, /* delta **/
update comment

2024-06-11 18:18 UTC, snreynolds commented on src/test/EmptyRevertHook.sol
> +        BalanceDeltas, /* delta **/
update comment

2024-06-11 18:18 UTC, snreynolds commented on src/test/EmptyRevertHook.sol
> +        BalanceDeltas, /* delta **/
update comment

2024-06-11 18:18 UTC, snreynolds commented on src/test/EmptyRevertHook.sol
> +        BalanceDeltas, /* delta **/
same

2024-06-11 18:18 UTC, snreynolds commented on test/types/BalanceDeltas.t.sol
> +// SPDX-License-Identifier: UNLICENSED
same as the other lib, Could you do the rename first and then the changes to the name inside the file after? its hard to analyze the diff when it shows it as an entirely new file

2024-06-11 18:18 UTC, snreynolds commented on src/types/BeforeSwapDeltas.sol
> +// SPDX-License-Identifier: MIT
Could you do the rename first and then the changes to the name inside the file after? its hard to analyze the diff when it shows it as an entirely new file

2024-06-12 04:09 UTC, mergd commented
junior

2024-06-14 20:53 UTC, snreynolds commented on src/interfaces/IHooks.sol
> +    /// @param deltas The amount owed to the caller (positive) or owed to the pool (negative)
this still is amount not amounts

2024-06-17 17:39 UTC, snreynolds reviewed
Looks good, few comments.

What is the test/.DS_STORE file being added though?

2024-06-17 17:39 UTC, snreynolds commented on src/test/CustomCurveHook.sol
> +        BalanceDeltas, /* delta **/
update comment

2024-06-17 17:39 UTC, snreynolds commented on src/libraries/Hooks.sol
> +        if (hookDeltasUnspecified != 0 || hookDeltaSpecified != 0) {
this should be `hookDeltaUnspecified` no? Its just 1 number

2024-06-17 19:35 UTC, snreynolds submitted a review, later dismissed

2024-06-18 15:37 UTC, snreynolds requested changes
tests failing, need to fix imports

2024-06-18 17:01 UTC, snreynolds reviewed
CI still broken! gotta lint

2024-11-06 16:47 UTC, closed without merging