:heavy_plus_sign: Add global usage of PoolIdLibrary for PoolKey
Uniswap/v4-core pull request #819
Opened 2024-08-07 09:30 UTC by GianfrancoBazzani

This addition will allow the usage of the method `PoolKey.toId()` without require to import the `PoolIdLibrary` and use the `using PoolIdLibrary for PoolKey` directive.

2024-08-13 19:53 UTC, hensha256 requested changes

2024-08-13 19:53 UTC, hensha256 commented on src/types/PoolKey.sol
> +using PoolIdLibrary for PoolKey global;
can you then remove `using PoolIdLibrary for PoolKey` frm all the contracts where it is used?

2024-08-13 19:53 UTC, hensha256 commented on src/types/PoolKey.sol
> +using PoolIdLibrary for PoolKey global;
Please can you also sign your commit :)

2024-08-17 14:11 UTC, GianfrancoBazzani commented
* hey @hensha256 thanks for the suggestion!  It should be ok now. Added also corresponding PR to v4-periphery repo: https://github.com/Uniswap/v4-periphery/pull/300

2024-08-29 20:43 UTC, hensha256 submitted a review, later dismissed

2024-08-30 12:36 UTC, hensha256 commented
Hi! Sorry you have some merge conflicts form another PR we merged. Please can you fix those?

2024-08-30 14:53 UTC, GianfrancoBazzani commented
Done!

2024-08-30 17:33 UTC, hensha256 approved these changes

2024-08-30 18:04 UTC, merged