SB I01: custom error on ERC6909 transferFrom / allowance
Uniswap/v4-core pull request #833
Opened 2024-08-20 18:35 UTC by saucepoint

## Related Issue

Spearbit board 36

## Description of changes

Add a custom revert `InsufficientAllowance` for ERC6909 transferFrom

Do we want a custom revert for InsufficientBalance? right now its reverting with arithmetic overflow/underflow, but hey at least its distinguished from allowance reverts

2024-08-20 19:45 UTC, snreynolds requested changes

2024-08-20 19:45 UTC, snreynolds commented on src/ERC6909.sol
> +                if (amount > allowed) revert InsufficientAllowance();
use CustomRevert lib

2024-08-26 12:20 UTC, hensha256 commented
> Do we want a custom revert for InsufficientBalance? right now its reverting with arithmetic overflow/underflow, but hey at least its distinguished from allowance reverts

Yeah I'd say if we're doing this then we should do it properly i guess. So lets have `InsufficientBalance` too

2024-09-05 21:59 UTC, snreynolds commented
rip 💀

2024-09-05 21:59 UTC, closed without merging